# Generated by Django 4.0.8 on 2022-11-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_profile',
        ),
    ]
